services:
  db:
    image: postgres
    port:
      - 5434:5432
    volumes:
      - data: /var/lib/postgres
    environment:
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
      - POSTGRES_DB=movies
    restart: always
    container_name: db
  backend:
    image: movies:1.0
    port:
      - 8085:8085
    environment:
      - DEV_DB_URL_DOCKER=jdbc:postgresql://db:5432/movies
      - DEV_DB_USERNAME=user
      - DEV_DB_PASSWORD=user
    restart: always
volumes:
  data:
    driver: local
